#!/bin/sh

# ライブラリ読み出し
source "$(dirname $0)/library.sh"


# 機密情報の読み出し
if [ "$SECRET_FILE" != '' -a -f "$SECRET_FILE" ]; then
  source "$SECRET_FILE"
fi


# パスフレーズ読み取り
INTER_CA_PASSWORD="${INTER_CA_PASSWORD:=""}"
if [ "$INTER_CA_PASSWORD" == '' ]; then
  readPassword \
    "Input intermediate CA passphrase: " \
    INTER_CA_PASSWORD
fi

SERVER_PASSWORD="${SERVER_PASSWORD:=""}"
if [ "$SERVER_PASSWORD" == '' ]; then
  verifyPassword \
    'Input private key passphrase:' \
    'Verify private key passphrase:' \
    SERVER_PASSWORD

  if [ $? -ne 0 ]; then
    echo 'Password mismatch' > /dev/stderr
    exit 1
  fi
fi


# 初期化
ROOT_CA_DIR="${ROOT_CA_DIR:="/etc/ssl/root_ca"}"
INTER_CA_DIR="${INTER_CA_DIR:="/etc/ssl/inter_ca"}"


# ドメイン名(DN; Distinguished Name)
DN="${DN:="apps.localdomain"}"
SUBJECT="${SUBJECT:="/C=JP/CN=$DN"}"
SAN="${SAN:="DNS:$DN,DNS:app1.apps.localdomain"}"


# 鍵生成
openssl genrsa \
  -batch \
  -passout "pass:$SERVER_PASSWORD" \
  -out "$INTER_CA_DIR/private/$DN.pem" \
  -aes-256-cbc \
  4096

if [ $? -ne 0 ]; then
  echo 'Failed to generate ras key.' > /dev/stderr
  exit 1
fi


# パスフレーズレス秘密鍵生成
openssl rsa \
  -passin "pass:$SERVER_PASSWORD" \
  -in "$INTER_CA_DIR/private/$DN.pem" \
  -out "$INTER_CA_DIR/private/$DN.nopass.pem"

if [ $? -ne 0 ]; then
  echo 'Failed to generate ras key without passphrase.' > /dev/stderr
  exit 1
fi

# リクエスト
openssl req -new -utf8 \
  -batch \
  -subj "$SUBJECT" \
  -addext "subjectAltName = $SAN" \
  -passin "pass:$SERVER_PASSWORD" \
  -keyform PEM \
  -key "$INTER_CA_DIR/private/$DN.pem" \
  -out "$INTER_CA_DIR/requests/$DN.csr"

if [ $? -ne 0 ]; then
  echo 'Failed to generate requeset.' > /dev/stderr
  exit 1
fi


# 署名
openssl ca \
  -batch \
  -config "$CONFIG_FILE" \
  -section CA_inter \
  -extensions web_server_ca \
  -md sha256 \
  -days 366 \
  -passin "pass:$INTER_CA_PASSWORD" \
  -keyform PEM \
  -keyfile "$INTER_CA_DIR/private/private_key.pem" \
  -cert "$INTER_CA_DIR/certs/inter_ca.crt" \
  -in "$INTER_CA_DIR/requests/$DN.csr" \
  -out "$INTER_CA_DIR/certs/$DN.crt"

if [ $? -ne 0 ]; then
  echo 'Failed to generate certificate.' > /dev/stderr
  exit 1
fi


# チェーン生成
openssl crl2pkcs7 \
  -nocrl \
  -certfile "$INTER_CA_DIR/certs/$DN.crt" \
  -certfile "$INTER_CA_DIR/certs/inter_ca.crt" \
  -certfile "$ROOT_CA_DIR/certs/root_ca.crt" \
  -out "$INTER_CA_DIR/certs/$DN.chain.p7b"

if [ $? -ne 0 ]; then
  echo 'Failed to generate certificate chain.' > /dev/stderr
  exit 1
fi


# Nginx向け証明書チェーン
cat "$INTER_CA_DIR/certs/$DN.crt"      >  "$INTER_CA_DIR/certs/$DN.chain.crt"
cat "$INTER_CA_DIR/certs/inter_ca.crt" >> "$INTER_CA_DIR/certs/$DN.chain.crt"
cat "$ROOT_CA_DIR/certs/root_ca.crt"   >> "$INTER_CA_DIR/certs/$DN.chain.crt"
