#!/bin/sh

# ライブラリ読み出し
source "$(dirname $0)/library.sh"


# 機密情報の読み出し
if [ "$SECRET_FILE" != '' -a -f "$SECRET_FILE" ]; then
  source "$SECRET_FILE"
fi


# パスフレーズ読み取り
INTER_CA_PASSWORD=${INTER_CA_PASSWORD:=''}
if [ "$INTER_CA_PASSWORD" == '' ]; then
  readPassword \
    "Input intermediate CA passphrase: " \
    INTER_CA_PASSWORD
fi


# 初期化
INTER_CA_DIR="${INTER_CA_DIR:="/etc/ssl/inter_ca"}"

INTER_CA_OCSP_DOMAIN="${INTER_CA_OCSP_DOMAIN:="ca.localdomain"}"
INTER_CA_OCSP_PORT="${INTER_CA_OCSP_PORT:=2561}"


# OCSPサーバー
openssl ocsp \
  -url "$INTER_CA_OCSP_DOMAIN:$INTER_CA_OCSP_PORT" \
  -port "$INTER_CA_OCSP_PORT" \
  -timeout $OCSP_TIMEOUT \
  -passin "pass:$INTER_CA_PASSWORD" \
  -index "$INTER_CA_DIR/index.txt" \
  -rkey "$INTER_CA_DIR/private/private_key.pem" \
  -rsigner "$INTER_CA_DIR/certs/inter_ca.crt" \
  -CA "$INTER_CA_DIR/certs/inter_ca.crt"
