#!/bin/sh

# ライブラリ読み出し
source "$(dirname $0)/library.sh"


# 機密情報の読み出し
if [ "$SECRET_FILE" != '' -a -f "$SECRET_FILE" ]; then
  source "$SECRET_FILE"
fi


# パスフレーズ読み取り
ROOT_CA_PASSWORD=${ROOT_CA_PASSWORD:=""}
if [ "$ROOT_CA_PASSWORD" == '' ]; then
  readPassword \
    "Input root CA passphrase: " \
    ROOT_CA_PASSWORD
fi


# 初期化
ROOT_CA_DIR="${ROOT_CA_DIR:="/etc/ssl/root_ca"}"

ROOT_CA_OCSP_DOMAIN="${ROOT_CA_OCSP_DOMAIN:="ca.localdomain"}"
ROOT_CA_OCSP_PORT="${ROOT_CA_OCSP_PORT:=2560}"


# OCSPサーバー
openssl ocsp \
  -url "$ROOT_CA_OCSP_DOMAIN:$ROOT_CA_OCSP_PORT" \
  -port "$ROOT_CA_OCSP_PORT" \
  -timeout $OCSP_TIMEOUT \
  -ignore_err \
  -multi 1 \
  -passin "pass:$ROOT_CA_PASSWORD" \
  -index "$ROOT_CA_DIR/index.txt" \
  -rkey "$ROOT_CA_DIR/private/private_key.pem" \
  -rsigner "$ROOT_CA_DIR/certs/root_ca.crt" \
  -CA "$ROOT_CA_DIR/certs/root_ca.crt"
