#!/bin/sh

# ライブラリ読み出し
source "$(dirname $0)/library.sh"

# 環境の読み出し
if [ -f "$(dirname $0)/.env" ]; then
  source "$(dirname $0)/.env"
fi

if [ "$SECRET_FILE" != '' -a -f "$SECRET_FILE" ]; then
  source "$SECRET_FILE"
fi


# 設定ファイルのディレクトリ
CONFIG_DIR="${CONFIG_DIR:="."}"

# 初期化
ROOT_CA_DIR="${ROOT_CA_DIR:="/etc/ssl/root_ca"}"
INTER_CA_DIR="${INTER_CA_DIR:="/etc/ssl/inter_ca"}"

# ドメイン名(DN; Distinguished Name)
DN="${DN:="apps.localdomain"}"
CRL_REASON=${CRL_REASON:="superseded"}

# パスフレーズ読み取り
INTER_CA_PASSWORD=''
readPassword \
  "Input intermediate CA passphrase: " \
  INTER_CA_PASSWORD


# 失効
openssl ca \
  -batch \
  -config "$CONFIG_DIR/openssl.cfg" \
  -section CA_inter \
  -extensions inter_ca \
  -md sha256 \
  -passin "pass:$INTER_CA_PASSWORD" \
  -keyform PEM \
  -keyfile "$INTER_CA_DIR/private/private_key.pem" \
  -cert "$INTER_CA_DIR/certs/inter_ca.crt" \
  -revoke "$DN.crt" \
  -crl_reason "$CRL_REASON"

if [ $? -ne 0 ]; then
  echo 'Failed to revoke certificate.' > /dev/stderr
  exit 1
fi
